controller:
  type: rl  # pd | rl | nn_pd
  params:
    kp: 150.0
    kd: 20.0

trajectory:
  type: neural  # classic | neural
  params:
    amplitude: 1.0
    frequency: 0.5

simulation:
  duration: 200
